- README.rst
- fades/parsing.py
- tests/test_parsing.py
Code and tests, not only adding the functionality for "projectname" itself, but also exploding on bad comparisons like "<>".
Note: when we search for a comment, before we find "fades.pypi", we just log in warning, but after that the syntax is rigid, so if the user fails to write that properly and we don't understand it, it's better to raise an Exception.
> Support package names in the module comments. Fixes #17.

- fades/logger.py
I think there's no point in polluting stdout for user *everytime she runs fades* because syslog is not configured; it's not our business.
So, if there is a syslog, use it. Else, don't use it :)
> Ignore silently that syslog is not configured.

- fades/pipmanager.py
This should avoid having to install pip many times in the same run, as evidenced by this log:
```
*** fades ***  2015-07-04 23:50:28,439  fades.pipmanager   INFO     Need to install a dependency with pip, but no builtin, do it manually
*** fades ***  2015-07-04 23:50:39,776  fades.pipmanager   INFO     Installing dependency: RandomWords==0.1.12
*** fades ***  2015-07-04 23:50:47,016  fades.pipmanager   INFO     Need to install a dependency with pip, but no builtin, do it manually
*** fades ***  2015-07-04 23:50:50,136  fades.pipmanager   INFO     Installing dependency: amqp==1.4.6
*** fades ***  2015-07-04 23:50:53,845  fades.pipmanager   INFO     Need to install a dependency with pip, but no builtin, do it manually
*** fades ***  2015-07-04 23:50:56,875  fades.pipmanager   INFO …
```
> dont install pip every time

- README.rst
- fades/main.py
- man/fades.1
Added an option use ipython instead of python shell. 
The option is -i | --ipython. This option add ipython as a dependency.
Examples:
`$ fades -i -d requests`
`$ echo "import requests; print(requests.__version__)" > foo.py`
`$ fades -i -d requests foo.py -i`
In the last example, first *i* means "use IPython" while second *i* is a parameter to IPython shell indicating that we want to use interactive session.
> added an option to execute ipython

- DEVELOPMENT.rst
- README.rst
- fades/main.py
- requirements.txt
- test
With these changes it's now possible to simply run the tests using the 'test' script without previously having to install the dependencies system-wide or in a virtualenv.
> run tests using fades to install the necessary dependencies

- fades/envbuilder.py
There are many situations where pip doesn't install inside the venv. So with this 're check' we will avoid its.
> Re check if pip was installed. 

- README.rst
- fades/cache.py
- fades/envbuilder.py
- fades/main.py
- man/fades.1
- tests/test_cache.py
- tests/test_envbuilder.py
This PR introduces a new --rm flag for fades that allows it to remove the virtualenv matching the specified dependencies.
> Remove virtualenv

- fades/main.py
> Seding de real interpreter path instead of the one that we store

- README.rst
- fades/cache.py
- fades/envbuilder.py
- fades/main.py
- man/fades.1
- tests/test_envbuilder.py
Hi, this PR is related to issue #170. 
With this pull request i've added this behaviors:
* When fades is invoked, always test the existence of usage_stats file. If it doesn't exists, it's created and filled with all the current venvs in cache.
* When venv it's used one line is recorded in usage file. This line contains the venv's uuid and datetime of usage.
* When fades is called with the option *--clean-unused-venvs=X*; after the first check, the usage file is compacted and all venvs that haven't been used for more than X days are removed. That's mean, remove from usage stat file, from index and the fisical env.
> Clean old venvs

- fades/envbuilder.py
- tests/test_envbuilder.py
When a dependency fail to be installed, the process call to destroy_venv with no cache parameter and fails.
This problem was not detected by tests because the assert was in the same scope where the exception it's captured.
> if no cache in params, then only remove folder. Fix test

- fades/envbuilder.py
- tests/test_envbuilder.py
Studied the relation between venvscache, venvbuilder, and who used them.
VEnvsCache is the cache, only, and shouldn't have action over the rest of the system.
I initially thought that we could move more stuff into FadesEnvBuilder, but not really, the best interface was to have creation and removing at module's level. So why to have FadesEnvBuilder as a class??? well, just to reuse virtualenv's EnvBuilder, so I just changed it's name to make it private in the module and improved its docstring.
Also, moved out the path removal from FadesEnvBuilder to the module's destroy_venv, which is the preferred interface.
> Improve the env building interfaces. Fixes #200.

- build_readme
- testdev
It looks that originally they weren't included...
> Useful scripts, again (?)

- fades/pipmanager.py
- tests/test_pipmanager.py
In the case pip isn't installed on the current virtualenv, the PipManager downloads a `get-pip.py` script that bootstraps it. If you cancel the download or something goes wrong, the file gets created but might be incomplete. If you retry, you get an error because it asumes it already has the `get-pip.py`.
This pull request makes the file downloading more atomic by first downloading to a temp file and only after complete copying to the definitive file.
> Cleanup if pip download fails

- fades/main.py
- Change `sys.platform` to `platform.platform()` inside a `print()` for `--version`.
- 3 lines change, but logs better info about the system on the log, minor, tests pass Ok.
> Returns a single string identifying the underlying platform with as much useful information as possible.
> The output is intended to be human readable.
**Before:**
```python
System: linux
```
**After:**
```python
System: Linux-4.11.5-1-ARCH-x86_64-with-Archlinux
```
> Log platform info using platform.

- AUTHORS
I wonder if we should include something like the following in a test case:
```
$ fades -d pyuca
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyuca import Collator
>>> authors = open('AUTHORS', 'rt', encoding='utf8').readlines()
>>> authors == sorted(authors, key=Collator().sort_key)
True
```
> Ordered AUTHORS and included Juan Carlos Paco.

- tests/test_envbuilder.py
one tests wasn't deleting tmp files 
```
/tmp  tree tmp*                                                                                                                                                    5ms 
tmp14aoscfc                                                                                                                                                              
└── usage_stats                                                                                                                                                          
tmp1nx0ux37                                                                                                                               
tmp1sjmitat …
```
> delete temp folder used for tests

- fades/helpers.py
- test
```
~/code/fades   better_exit  ack --python 'exit\('                                                                                                             4100ms 
fades/envbuilder.py
87:            sys.exit(1)
90:            sys.exit(2)
93:            sys.exit(3)
149:                sys.exit(4)
fades/main.py
156:        sys.exit(0)
169:        sys.exit(-1)
190:            sys.exit(rc)
265:                sys.exit(1)
326:    sys.exit(rc)
fades/helpers.py
138:            sys.exit(1)
253:            sys.exit(1)
```
> always use sys.exit(). resolve #280

- fades/cache.py
```
✘  ~/code/fades   master ●  ./bin/fades -v -d aldas                                                                                                          1050ms 
*** fades ***  2018-03-25 13:37:07,837  fades              DEBUG    Running Python sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0) on 'Linux-4.15.12-1-ARCH-x86_64-with-arch'
*** fades ***  2018-03-25 13:37:07,838  fades              DEBUG    Starting fades v. 6.1
*** fades ***  2018-03-25 13:37:07,838  fades              DEBUG    Arguments: Namespace(check_updates=False, child_options=[], child_program=None, clean_unused_venvs=None, dependency=['aldas'], executable=False, ipython=False, no_precheck_availability=False, pip_options=[], python=None, python_options=[], quiet=False, remove=None, …
```
> remove a duplicated log. resolve #263

- fades/main.py
It's tested in my local. I was trying to add some tests and I wasn't able to. 
tl;dr:  tests are running in a virtualenv. And fades doesn't support running in a venv. 
I think for the next release we should do some refactor in `go()` splitting it in smaller pieces to allow testing.
Then we can add tests for fades.main
> not crash if executable is not there. resolve #261

- AUTHORS
- fades/parsing.py
- tests/test_parsing.py
This PR includes changes to fix the issue #316 
- Adds a patch for [parsing._parse_content()](https://github.com/PyAr/fades/blob/master/fades/parsing.py#L91)
- Added log
- Added new tests cases
> Fix line parsing

- bin/fades
- fades/__init__.py
- fades/__main__.py
- fades/envbuilder.py
- fades/helpers.py
- fades/main.py
- testdev.bat
- tests/test_envbuilder.py
- tests/test_helpers.py
Pass exceptions to the main module instead of sys.exiting.
> Replace sys.exit calls with exceptions

- man/fades.1
Fix a typo warned by lintian.
> I: fades: spelling-error-in-manpage usr/share/man/man1/fades.1.gz SYNOPSYS SYNOPSIS
> man/fades.1: Fix typo on synopsis header

- fades/main.py
- man/fades.1
Two things, mainly:
- stopped passing a custom "usage" to ArgumentParser (which was heavily out of date); now we rely in the automatically built "usage", which is identical (but with all the options).
- I double-checked the `man` to see if it was complete, and --no-precheck-availability was missing! Added that (and improved the message also in the arg parsing).
> Improvements to usage and man. Fixes #304.

- requirements.txt
- tests/test_envbuilder.py
Removed mccabe, pycodestyle and pyflakes from the requirements, as all those are dependencies from flake8 itself.
Also included some fixes for issues this version now detects.
> Update pep8 related libs.

- .gitignore
- tests/test_infra.py
I found that `test_flake8_pytest` is using .flake8 file instead of `FLAKE8_OPTIONS`.
To reporduce this error you can delete .flake8 file and run `./test`, this will fail with a lot of ` E501 line too long`. 
With this patch I fixed this behavior.
> Fix use of flake8.get_style_guide

- README.rst
- fades/main.py
- fades/parsing.py
- man/fades.1
- testdev
- tests/test_main.py
- tests/test_pkgnamesdb.py
This is done by passing a temp file that does the importing, then leaving the user in the interactive interpreter.
Changing PYTHONPATH was explored, but it was too difficult because a) needing to support *current* PYTHONPATH setting, and b) ipython does not respect that envvar.
Of course, there's no collision for `-i` because the fades is call is *without script at all*, this is enabled only for the interactive interpreter case.
While doing this, I also improved a little the "package names db" and its usage, as I needed the "reverse case" of it.
Also, changed my mind about doing this by default, as I proved more "hacky" than I expected. It's not important, though, if you want to always have it enabled, you can use `--autoimport` in your user's config.
> Created --autoimport parameter to autoimport indicated dependencies.

- README.rst
- fades/main.py
- man/fades.1
- tests/test_main.py
This has several details:
- Improve docs: man, argument help and specially README, where I separated
it's explanation to a different section.
- Allow an absolute path to be given beyond a simple name (but
not relative paths!).
- Made it mandatory to include a child_program if --exec is used.
Also, two small fixes: fixed program name in argparse, and included a
forgotten --autoimport reference in the man.
> Extended/normalized the --exec parameter behaviour.

- README.rst
- fades/main.py
- man/fades.1
- tests/test_main.py
Made it mutually exclusive with -x/--exec.
Also improve the name of the variable of the process, and refactored what is logged when executing a script/module: it's now more explicit, I tried it and provides more information yet being more simple.
> Added support for native -m/--module.

- fades/pipmanager.py
- tests/test_pipmanager.py
Windows can't use pip.exe and delete it while it is using it.
Just follow the indication given and use python -m pip install pip --upgrade instead.
> Fixed Windows Issue

- fades/main.py
This fixes the situation where a file (where fades is used in the shebang) name has spaces.
> Don't do any special for shebang parameters as they come normally.

- .github/workflows/tests.yaml
- upgrade actions to base on nodejs 20 runtime
> chore: upgrade action deps

- AUTHORS
- README.rst
- fades/main.py
- man/fades.1
A quick change to address the following issues:
- #418  : added `-U` as a synonym for `--check-updates` and updated `man` page
- #409 : added `--where` as a synonym for `--get-venv-dir` and updated `man` page
> cli synonyms for --get-venv-dir and --check-updates

- .github/workflows/integtests.yaml
- tests/integtest.py
Integration tests running on:
- Ubuntu
- Arch
- Fedora
- Windows
- MacOS
This is just a simple fades execution and also a run using a different Python version.
> Added integration tests in a lot of different platforms

- .github/workflows/integtests.yaml
- README.rst
- fades/envbuilder.py
- man/fades.1
- tests/test_envbuilder.py
Previously we used 'virtualenv' to mean 'virtual environment', but it confuses everything because of the equally named `virtualenv` tool.
> Stop using the term virtualenv

- .github/workflows/integtests.yaml
- README.rst
- fades/cache.py
- fades/envbuilder.py
- fades/helpers.py
- fades/parsing.py
- pkg/debian/control
- pkg/snap/snapcraft.yaml
- requirements.txt
- setup.py
- tests/__init__.py
- tests/test_cache/__init__.py
- tests/test_envbuilder.py
- tests/test_helpers.py
- tests/test_infra.py
- tests/test_main.py
- tests/test_parsing/test_vcs_dependency.py
The replacement is the `packaging` module, but it's not exactly the same. It provides a `Requirement` object but it's different from the previous one, and there's no `Dependency` so to match versions we need to play with `Requirement.specifiers`.
The `VCSDependency` object we had grew in complexity, as it needs a new `VCSSpecifier` to mimic the new `Requirement`. Similarly, I added a `NameVerDependency` to be able to compare objects with name and version.
While working on this I found that in `check_pypi_updates` we were comparing versions as strings ("2.3" is greater than "1.3", but it is smaller than "10.2"... and if you compare the strings that is broken). I added a test for this and fixed it by using `packaging.Version` which compare as they should.
Finally, I removed all traces of …
> Stopped using pkg_resources, as it's deprecated.

- .github/workflows/integtests.yaml
- README.rst
- fades/_version.py
- fades/envbuilder.py
- fades/file_options.py
- fades/main.py
- man/fades.1
- pkg/debian/control
- pkg/debian/copyright
- setup.py
- tests/test_envbuilder.py
This is possible now as we're living in the future already (?): Python minimum version is now 3.6, which is old enough.
While it simplifies the code a lot, there may be some breakage. 
If the user is passing specific options to `virtualenv`, as we don't use it anymore, what to do? For that I added the possibility of passing options to the `venv` module itself... the user may need to change something in their scripts, but at least the can keep things in control.
Also I improved the README, stopped using "virtualenv" to mean "virtual environment" as it was too confusing. Being explicit now.
> Only use the `venv` module to create virtualenvs.

- bin/fades
MacOS lacks the `packaging` package by default. So running `bin/fades -V` fails with a stack trace.
This change is to show a more readable error when the required package is missing.
> Show an error if the `packaging` dependency is not present
