PyAr/fades

fades/cache.py
fades/parsing.py
fades/pipmanager.py
tests/test_cache.py
tests/test_parsing.py

To try this, please remove previous cache index files that you may have 
(In the future we would need to have format conversions for this kind of improvement, but no need to suffer that pain now, as cache is not yet released... it didn't stay in master more than a day :p )

Store and use version comparison and value separatedly. Fixes #37

---

fades/parsing.py
setup.py

Name changing package support. Also long_description and fixes to setup.py

Name changing pkg

---

fades/helpers.py
fades/pipmanager.py
tests/test_pipmanager.py

@facundobatista pegale una mirada porque tal vez hay una manera más linda de buscar dentro del stdout. :see_no_evil:

getting dependency version with pip fixed. resolve #65

---

test

hidding `type` stderr out

---

README.rst
fades/cache.py
fades/envbuilder.py
fades/main.py
fades/pipmanager.py
man/fades.1
tests/test_cache.py
tests/test_envbuilder.py
tests/test_pipmanager.py

Also --virtualenv-options and --pip options to pass custom settings to each one
Please test it.

New --system-site-packages option. 

---

pkg/archlinux/PKGBUILD

https://aur.archlinux.org/packages/fades/

Archlinux release 4.0

---

README.rst
man/fades.1

Also, added some old options to syntax in man.

Info for --check-updates. Fixes #158.

---

README.rst
man/fades.1

Config files man

---

fades/__init__.py
fades/_version.py
fades/main.py
setup.py
tests/test_main.py

Change Version to Tuple

---

fades/envbuilder.py
fades/pipmanager.py
tests/test_envbuilder.py
tests/test_pipmanager.py

Remove VirtualEnv on dependency Failure

---

fades/envbuilder.py
tests/test_envbuilder.py

Hi, this is a fix to the issue #193.

destroy_env now is a static method instead of a instance one

---

fades/helpers.py
tests/test_helpers.py

Create base directories if nonexistant. Several tests added. Fixes #204.

Create base directories if nonexistant. Several tests added.

---

fades/main.py

Except for ctrl-c, which we swallow. See comment in the code.

Send the signals *also* to the interactive interpreter. Fixes #191.

---

README.rst

I always wanted to be part of this amazing project!

Fix really important error about --pip-options argument

---

fades/envbuilder.py
fades/main.py
tests/test_envbuilder.py

Copate y mergealo! :-p :-) :+1: :1234: :8ball: 
ni se lo que hace este software, pero ahí va el issue #233 para que lo disfruten

Issue 233 exit 0 is bad

---

fades/pipmanager.py
tests/test_pipmanager.py

make sure we show the version if we are going to log something.
feel free to make suggestions for more reasonable strings.

say hi on first call of pipmanager.install

---

fades/pipmanager.py
tests/test_pipmanager.py

Support multiword dependencies. 

---

setup.py

See here on how I played with the original problem and solution: http://linkode.org/gWHaB1lar9IVP4gab9fPT3

Forbid installation under Python 2. Fixes #221.

---

.appveyor.yml

Note that appveyor is not green, but making it pass is beyond this branch (but will keep the relevant issue open)

Integrate appveyor

---

README.rst

Congrats on the snap of fades. Here's a badge to show the current snap build status.

Add a snapcraft (https://snapcraft.io) badge

---

.travis.yml

related to: https://github.com/travis-ci/travis-ci/issues/9069

remove nightly from tests. 

---

fades/main.py
tests/test_main.py

resolves #279 
:warning: Whit this solution we are only avoiding duplicated by repo.

don't duplicate dependencies by repo

---

.travis.yml

only run coveralls for python3.6

---

AUTHORS
fades/main.py

Use system-independent path separator.

Use os.pathsep

---

README.rst
fades/main.py
man/fades.1
tests/test_main.py

I'll update the PR with documentation patches after we come up with the proper solution.

Multiple requirement files support

---

fades/helpers.py
tests/test_helpers.py

Supports different backends, and is super easy to add new ones.
Currently supported (check them out!):
- Raw, no real pastebin backend: `http://taniquetil.com.ar/tmp/notif.py`
- Linkode (the best pastebin, of course): `http://linkode.org/#r7H5p56PWYjT9EkXmByTd4`
- Pastebin itself: `https://pastebin.com/pSwmqrZu`
- Github's GIST: `https://gist.github.com/facundobatista/ba8f25bef112450d48a9d33b4b3fda70`

Support several pastebines to download code.

---

fades/helpers.py

Use new PyPI domain for checking projects and their info.

---

fades/main.py

Don't precheck-availability when no dependencies

---

.appveyor.yml
.travis.yml
requirements.txt
setup.py
test
testdev
testdev.bat

This pull requests changes nosetest by pytest. 
I modified:
* config files:
- requirements.txt
- setup.py
* ci file:
- .appveyor.yml
- .travis.yml
* scripts
- test 
- testdev
- testdev.bat

pytest I: replaced test runner: pytest instead of nosetest.

---

README.rst
fades/main.py
man/fades.1
tests/test_main.py

Improved main module: how loggers are used (and affecting params, made them mutually exclusive) and style consistency.

---

README.rst

resolve #412. Change the example to /usr/bin/env fades
